name: Build Flutter APK & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true # کش گرفتن برای سرعت بالا

      - name: Install dependencies
        run: flutter pub get

      # --- بخش تست (مهم) ---
      - name: Run tests
        run: flutter test
      
      # --- بخش بررسی قالب (Linting) ---
      - name: Analyze code
        run: flutter analyze

      # --- بخش بیلد آندروید ---
      - name: Build APK Debug
        run: flutter build apk --debug
      
      - name: Build APK Release
        run: |
          flutter build apk \
            --release \
            --obfuscate \
            --split-per-abi
      
      # --- آپلود فایل خروجی ---
      - name: Upload APK Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-splits
          path: build/app/outputs/flutter-apk/

      # --- بیلد iOS (اختیاری) ---
      - name: Build iOS App
        if: runner.os == 'macos'
        run: flutter build ios --release --no-codesign
