buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    // ⚠️ این بخش مشکل geolocator و تمامی پکیج‌های اندرویدی را به صورت ریشه‌ای حل می‌کند
    project.ext {
        set('compileSdkVersion', 34)
        set('targetSdkVersion', 34)
        set('minSdkVersion', 24)
        set('buildToolsVersion', '34.0.0')
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
