buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        google()
        mavenCentral()
    }
}

// ⚠️ این بلوک دقیقاً مشکل geolocator_android را به طور مستقیم حل می‌کند
ext {
    compileSdkVersion = 34
    targetSdkVersion = 34
    minSdkVersion = 24
    buildToolsVersion = "34.0.0"
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
